# Generated by Django 5.1.4 on 2024-12-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemregistration',
            old_name='amount',
            new_name='가격',
        ),
        migrations.RenameField(
            model_name='itemregistration',
            old_name='name',
            new_name='이름',
        ),
        migrations.RenameField(
            model_name='itemregistration',
            old_name='info',
            new_name='정보',
        ),
        migrations.RemoveField(
            model_name='itemregistration',
            name='satisfaction',
        ),
        migrations.RemoveField(
            model_name='itemregistration',
            name='status',
        ),
        migrations.AddField(
            model_name='itemregistration',
            name='구매여부',
            field=models.CharField(blank=True, choices=[('false', '구매 X'), ('true', '구매 O')], default='false', help_text='구매 여부를 선택해 주세요.', max_length=100),
        ),
        migrations.AddField(
            model_name='itemregistration',
            name='만족도',
            field=models.IntegerField(blank=True, choices=[(1, '불만족'), (2, '보통'), (3, '만족')], help_text='(구매 후) 만족도를 선택하세요.', null=True),
        ),
        migrations.AddField(
            model_name='itemregistration',
            name='우선순위',
            field=models.CharField(blank=True, choices=[('one', '1순위'), ('two', '2순위'), ('three', '3순위')], default='one', help_text='구매 우선순위를 결정해 주세요.', max_length=7),
        ),
        migrations.AddField(
            model_name='itemregistration',
            name='이미지',
            field=models.ImageField(blank=True, null=True, upload_to='wish_images/'),
        ),
    ]
