# Generated by Django 5.1.4 on 2024-12-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atcl_no', models.CharField(max_length=50)),
                ('trad_tp_nm', models.CharField(max_length=20)),
                ('prc', models.CharField(max_length=50)),
                ('spc1', models.FloatField()),
                ('detail_url', models.URLField()),
            ],
        ),
    ]
