# Generated by Django 5.1.4 on 2024-12-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gocity_district', models.CharField(max_length=100, verbose_name='시군구')),
                ('complex_name', models.CharField(max_length=100, verbose_name='단지명')),
                ('rent_type', models.CharField(max_length=10, verbose_name='전월세구분')),
                ('area', models.FloatField(verbose_name='적용면적(㎡)')),
                ('contract_year_month', models.CharField(max_length=6, verbose_name='계약년월')),
                ('deposit', models.CharField(max_length=20, verbose_name='보증금(만원)')),
                ('monthly_rent', models.CharField(blank=True, max_length=20, null=True, verbose_name='월세금(만원)')),
                ('housing_type', models.CharField(max_length=50, verbose_name='주택유형')),
                ('direction', models.CharField(blank=True, max_length=10, null=True, verbose_name='방향')),
            ],
        ),
    ]
