# Generated by Django 5.1.4 on 2024-12-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealEstateData',
        ),
    ]
