# Generated by Django 5.1.4 on 2024-12-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='city_district',
            new_name='gocity_district',
        ),
    ]
