# Generated by Django 5.1.4 on 2024-12-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_city_district_apartment_gocity_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='gocity_district',
            new_name='city_district',
        ),
    ]
